### ISSUE TITLE
Add Oxide icon for exe in directory view

### ISSUE THREAD

**Issue by lukespragg** [OxideMod/OxidePatcher#4]
![d2718893d6afce6d198c3f6bc958f23f](https://cloud.githubusercontent.com/assets/671337/4914053/a24c7ecc-64bc-11e4-9e2b-5dfc8ac0dede.png)

**Comment by HellUnit** [comment]
This seems to be an issue with the way travis does the builds I'm thinking. If you build it through VS, the icon gets added just fine. The travis builds however, are a different story. I've tried various methods and I can't get any of them to work. Not with an embedded icon anyway. It may be possible if an external .ico file was included in the directory and it was referenced as such. So far, it seems icon embedding doesn't play well with travis.

**Comment by lukespragg** [comment]
Well, it builds with Mono being as it is on Linux, so. ;)

**Comment by HellUnit** [comment]
Yeah, .NET support on Linux is always finicky whether it be Wine or Mono. I'm amazed it works so well with .NET 4.x to be honest. LOL. I'll see if I can get it to work with a non-embedded icon file.

**Comment by HellUnit** [comment]
I tried a few different methods of getting this to work today. I'm stumped. Someone with moar programming skillz than I may be able to get it, but I'm just not grasping it. The path is set to RustSTeam.ico in the manifest/IDE, but even when the .ico file is copied into the output directory, it still does not utilize it when built by travis. The builds through the IDE usually always work, so its hard to tell where exactly the problem is. I don't know if the path is wrong in the manifest or if travis isn't including the manifest, or its not being properly linked when being included as an embedded resource, or... or... or... *smoke pours from ears* ;-)

**Comment by lukespragg** [comment]
This is fixed now. Solution for Travis below:
``` yml
solution: OxidePatcher.sln /p:win32Icon="Resources/logo.ico"
```
